server:
  .port: ${PORT:8080}
spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: dummy01
  mail:
    host: smtp.gmail.com
    port: 587
    username: akhtermamoon1@gmail.com
    password: pyfa efyj zvlt nwad
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
