server:
  .port: 9091
spring:
  data:
    mongodb:
      uri: mongodb://dummy01:==@dummy01.mongo.cosmos.azure.com:10255/?ssl=true&retrywrites=false
      database: dummy01
  mail:
    host: smtp.gmail.com
    port: 587
    username: akhtermamoon1@gmail.com
    password: pyfa efyj zvlt nwad
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
